CREATE TABLE users(
    id           UUID PRIMARY KEY,
    email        VARCHAR(100),
    username     VARCHAR(100) NOT NULL,
    gender       VARCHAR(50),
    password     VARCHAR,
    picture      VARCHAR,
    auth_type    VARCHAR(50),
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ,
    deleted_at   TIMESTAMPTZ,
    CONSTRAINT unique_email_auth_type UNIQUE (email, auth_type)
);